version: "2.0"

services:
  webapp:
    image: node:18.9.0
    volumes:
     - "./webapp:/app"
    user: node
    working_dir: "/app"
    command: "bash -c 'npm ci && npm run watch'"
  
  server:
    image: golang:1.19.1
    restart: always
    volumes:
     - "./:/app"
    ports:
     - "8080:8080"
    environment:
     WEBDEV: "true"
    working_dir: "/app"
    command: "go run ."

  minetest:
    image: registry.gitlab.com/minetest/minetest/server:5.6.1
    user: root
    volumes:
    - "world_data:/root/.minetest/worlds/world"
    - "./minetest.conf:/etc/minetest/minetest.conf"
    ports:
    - "30000:30000/udp"
    command: ["/usr/local/bin/minetestserver", "--config", "/etc/minetest/minetest.conf"]

volumes:
  world_data: {}
