version: "2.0"

services:
  webapp:
    image: node:17.5.0
    volumes:
     - "./webapp:/app"
    user: node
    working_dir: "/app"
    command: "bash -c 'npm ci && npm run watch'"
  
  server:
    image: golang:1.17.7
    restart: always
    volumes:
     - "./:/app"
    ports:
     - "8080:8080"
    environment:
     WEBDEV: "true"
    working_dir: "/app"
    command: "go run ."