version: "2.0"

services:
  webapp:
    image: node:17.5.0-slim
    volumes:
     - "./webapp:/app"
    working_dir: "/app"
    command: "sh -c 'npm ci && npm run watch'"
  
  server:
    image: golang:1.17.7-alpine
    volumes:
     - "./:/app"
    working_dir: "/app"
    command: "go run ."